// Ping IndexNow (Bing, Yandex, etc.) with every URL in the built sitemap. Run after deploy.
//
// The sitemap is generated by src/pages/sitemap.xml.ts, so the only trustworthy
// source is a *fresh* build. Pinging a stale dist is how 51 dead URLs got
// submitted: the script used to read whatever happened to be in dist/.
import { readFileSync, existsSync, statSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = fileURLToPath(new URL('..', import.meta.url));
const KEY = '981882b5bcd524d6102160ac3044bcb9';
const HOST = 'sunrisegases.com';
const sitemapFile = join(repoRoot, 'dist', 'client', 'sitemap.xml');

const die = (msg) => {
  console.error(msg);
  process.exit(1);
};

if (!existsSync(sitemapFile)) die('No dist/client/sitemap.xml. Run `npm run build` first.');

/**
 * Newest mtime among *files* under the given files/dirs. Directories are not
 * counted: prebuild deletes stale public/ files, which bumps the public/ dir
 * mtime after the build and would otherwise flag every build as stale.
 * Dot-dirs are skipped (.astro/, .git/).
 */
function newestMtime(targets) {
  let newest = 0;
  for (const target of targets) {
    if (!existsSync(target)) continue;
    const walk = (p) => {
      const s = statSync(p);
      if (s.isDirectory()) {
        for (const e of readdirSync(p, { withFileTypes: true })) {
          if (e.name.startsWith('.')) continue;
          walk(join(p, e.name));
        }
      } else if (s.mtimeMs > newest) {
        newest = s.mtimeMs;
      }
    };
    walk(target);
  }
  return newest;
}

const sitemapMtime = statSync(sitemapFile).mtimeMs;
const newestSource = newestMtime([
  join(repoRoot, 'src'),
  join(repoRoot, 'public'),
  join(repoRoot, 'astro.config.mjs'),
]);

if (sitemapMtime < newestSource) {
  die('dist/client/sitemap.xml is older than src/ or public/ — rebuild with `npm run build` before running indexnow.');
}

const xml = readFileSync(sitemapFile, 'utf8');

// The generated sitemap has loc+lastmod only. <priority>/<changefreq> are the
// fingerprint of the retired hand-written sitemap, so treat them as a stale build.
if (/<priority>|<changefreq>/.test(xml)) {
  die('dist/client/sitemap.xml still has <priority>/<changefreq> — that is the retired hand-written sitemap. Rebuild and check for a public/sitemap.xml shadowing src/pages/sitemap.xml.ts.');
}

const urlList = [...new Set([...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]))];
if (!urlList.length) die('No <loc> entries found in dist/client/sitemap.xml — refusing to submit an empty sitemap.');

const res = await fetch('https://api.indexnow.org/IndexNow', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json; charset=utf-8' },
  body: JSON.stringify({ host: HOST, key: KEY, keyLocation: `https://${HOST}/${KEY}.txt`, urlList }),
});

const detail = (await res.text().catch(() => '')).trim();
// Per the IndexNow spec both are success: 200 = submitted, 202 = accepted with
// key validation pending. The endpoint returns either, so accept the 2xx range.
if (res.status !== 200 && res.status !== 202) {
  const reason = { 400: 'invalid format', 403: 'key not valid at keyLocation', 422: 'URLs do not belong to the host', 429: 'rate limited' }[res.status] ?? 'unexpected response';
  console.error(`IndexNow rejected the submission: HTTP ${res.status} (${reason})${detail ? ` — ${detail}` : ''}`);
  process.exit(1);
}
const note = res.status === 202 ? ' (accepted, key validation pending)' : '';
console.log(`IndexNow ${res.status} ${urlList.length} URLs${note}${detail ? ` — ${detail}` : ''}`);